<a href="https://colab.research.google.com/github/akshudurairaj/Applied-Linear-Algebra/blob/main/ALA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
from typing import Self




class Vec:


    def __init__(self, src=None) -> Self:
        if src is None:
            self.elements =()
        else:
            self.elements = tuple(src)

    def scalar_mult(self, alpha):
        el = list(self.elements)
        for i in range(len(el)):
            el[i] = el[i] * alpha
        return Vec(el)
        return result
    def __repr__(self):
        return repr(Self.elements)


if __name__ == "__main__":
    #z1 = Vec.zeros(10)
    v1 = Vec([10, 20, 30, 40, 50])
    v2=v1.scalar_mult(3)
    print(v2)
    print(v1)



AttributeError: elements

In [ ]:
from typing import Self


class Vec:

    def __init__(self, src=None) -> Self:
        if src is None:
            self.elements = ()
        else:
            self.elements = tuple(src)

    def scalar_mult(self, alpha):
        el = list(self.elements)

        for i in range(len(el)):
            el[i] = el[i] * alpha

        return Vec(el)

    def __repr__(self):
        return repr(self.elements)


if __name__ == "__main__":
    v1 = Vec([10, 20, 30, 40, 50])
    v2 = v1.scalar_mult(3)

    print(v2)
    print(v1)

(30, 60, 90, 120, 150)
(10, 20, 30, 40, 50)


In [ ]:
#without using list
from typing import Self


class Vec:

    def __init__(self, src=None) -> Self:
        if src is None:
            self.elements = ()
        else:
            self.elements = tuple(src)

    def scalar_mult(self, alpha):
        return Vec(tuple(x * alpha for x in self.elements))

    def __repr__(self):
        return repr(self.elements)


if __name__ == "__main__":
    v1 = Vec([10, 20, 30, 40, 50])
    v2 = v1.scalar_mult(3)

    print(v2)
    print(v1)

(30, 60, 90, 120, 150)
(10, 20, 30, 40, 50)


31/08/2026

In [5]:
#Array Basics
import numpy as np
a = np.array([1, 2, 3])
assert(a.dtype == np.int64)
a.shape

(3,)

In [8]:
assert (a.shape == (3,))

In [12]:

assert isinstance(a.shape, tuple)
a

array([1, 2, 3])

In [13]:
a.T

array([1, 2, 3])

In [14]:
a.T.shape

(3,)

In [16]:
x = [1, 2, 3]
x == [1, 2, 3]

True

In [17]:
a

array([1, 2, 3])

In [18]:
a == [1, 2, 3]

array([ True,  True,  True])

In [20]:
a == [1, 2, 0]

True

In [21]:
np.array_equal(a, [1, 2, 3])

False

In [23]:
all([True, False])

False

In [ ]:
a = np.random.rand(3, 3, 4)
assert(a.shape == (3, 3, 4))
assert(a.ndim == 3)

